# ===============================================================================
# Server Configuration
# ===============================================================================
#server.port=8081
server.port=${SERVER_PORT_PROD:8081}
#server.error.include-message=NEVER
server.error.include-message=ALWAYS
#
# ===============================================================================
# MySQL Database Configuration
# ===============================================================================
DB_QUERY_PARAMS=createDatabaseIfNotExist=false&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
#
#Local Database
spring.datasource.url=${SPRING_DATASOURCE_URL_LOCAL_PROD}/${DATABASE_NAME_LOCAL_PROD}?${DB_QUERY_PARAMS}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME_LOCAL_PROD}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD_LOCAL_PROD}
#
#Live Database
#spring.datasource.url=${SPRING_DATASOURCE_URL_LIVE_PROD}/${DATABASE_NAME_LIVE_PROD}?${DB_QUERY_PARAMS}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME_LIVE_PROD}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD_LIVE_PROD}
#
# ===============================================================================
# JPA / Hibernate Configuration
# ===============================================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
#
# ===============================================================================
# Actuator Configuration
# ===============================================================================
management.server.port=${MANAGEMENT_SERVER_PORT_FOR_ACTUATOR}
management.endpoints.web.base-path=${MANAGEMENT_ENDPOINTS_WEB_BASE_PATH_FOR_ACTUATOR}
management.endpoints.web.exposure.include=*
#management.endpoints.web.exposure.exclude=env,beans
management.endpoint.health.show-details=always
#
# ===============================================================================
# Logging Configuration
# ===============================================================================
LOG_LEVEL_MINIMUM_FOR_LOGBACK_SPRING=INFO
#
# ===============================================================================
# Other
# ===============================================================================
#
