# ===============================================================================
# Server Configuration
# ===============================================================================
server.port=${SERVER_PORT_DEV:8080}
server.error.include-message=ALWAYS
#
# ===============================================================================
# MySQL Database Configuration
# ===============================================================================
DB_QUERY_PARAMS=createDatabaseIfNotExist=false&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.url=${SPRING_DATASOURCE_URL_DEV}/${DATABASE_NAME_DEV}?${DB_QUERY_PARAMS}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME_DEV}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD_DEV}
#
# ===============================================================================
# JPA / Hibernate Configuration
# ===============================================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
#
# ===============================================================================
# Actuator Configuration
# ===============================================================================
management.server.port=${MANAGEMENT_SERVER_PORT_FOR_ACTUATOR}
management.endpoints.web.base-path=${MANAGEMENT_ENDPOINTS_WEB_BASE_PATH_FOR_ACTUATOR}
management.endpoints.web.exposure.include=*
#management.endpoints.web.exposure.exclude=env,beans
management.endpoint.health.show-details=always
#
# ===============================================================================
# Logging Configuration
# ===============================================================================
LOG_LEVEL_MINIMUM_FOR_LOGBACK_SPRING=INFO
#
# ===============================================================================
# Other
# ===============================================================================
#